apiVersion: v1
kind: Secret
metadata:
  name: expandox-lab-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/umario-chi/expandox-lab2.git
