apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
    name: finance-apps
    namespace: argocd
spec:
    description: "Applications for the Mini Finance Platform"

    # Allow manifests to be deployed from this Git repository
    sourceRepos:
        - "https://github.com/umario-chi/expandox-lab2.git"

    # Allow deployment to the 'mini-finance-dev' and 'mini-finance-prod' namespaces in the default cluster
    destinations:
        - namespace: mini-finance-dev
          server: https://kubernetes.default.svc
        - namespace: mini-finance-prod
          server: https://kubernetes.default.svc

    # Allow all cluster-scoped resources to be created
    clusterResourceWhitelist:
        - group: "*"
          kind: "*"

    # Allow all namespaced-scoped resources to be created
    namespaceResourceWhitelist:
        - group: "*"
          kind: "*"
