apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: mini-finance-app-prod
    namespace: argocd
spec:
    project: finance-apps
    source:
        repoURL: https://github.com/umarioi-chi/expandox-lab2.git
        targetRevision: main
        path: DevOps-Project-1/k8s/production
    destination:
        server: https://kubernetes.default.svc
        namespace: mini-finance-prod
    syncPolicy:
        automated:
            prune: true
            selfHeal: true
